### ISSUE TITLE
where do you set LS_COLORS and use the ls.fish

### ISSUE THREAD

**Issue by wprater** [ithinkihaveacat/dotfiles#1]
been using pieces of your fish setup, but curious how you get colorized to work with LS_COLORS and wen do you apply ls.fish?  I had to call it in config.fish `. $HOME/.config/fish/ls.fish`

**Comment by ithinkihaveacat** [comment]
Sorry I totally missed this question! So, it turns out I don't actually use the `ls.fish` in this repo… I'm not sure when I changed that, apologies for the confusion.

I do have colorized ls output, though, but it appears to happen via fish's standard [`ls.fish`](https://github.com/fish-shell/fish-shell/blob/master/share/functions/ls.fish) script, which aliases `ls` to `ls -G` on OS X, and something else on Linux. That doesn't work for you?
